### PR TITLE
change card design

### PR DESCRIPTION
**Pull request by krokrob**
@Papillard @arthur-littm I know that we will ship the new ui-components soon but I can't give our students our older card anymore. What do you think?
capture d ecran 2019-01-25 a 15 22 06
capture d ecran 2019-01-25 a 15 22 26

### CODE REVIEW

**Comment by krokrob** [comment]
We could also remove the `div.card-user`

**Comment by krokrob** [comment]
As an example of simple pattern relative/absolute, I would like to dig out the `badge`
capture d ecran 2019-01-25 a 16 46 46

**Comment by krokrob** [comment]
last update
capture d ecran 2019-01-25 a 17 42 35

**Comment by arthur-littm** [comment]
New `components` library should be out next week 👌

**Comment by arthur-littm** [comment]
Preview: https://lewagon-components.herokuapp.com/

**Comment by krokrob** [comment]
So cool!

**Comment by ssaunier** [comment]
ℹ️ FYI I think we'll go with `uikit.lewagon.com`

**Pull request closed without merging**
